name: Node CI

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2.5.1
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: yarn install
      run: yarn install
    - name: Linting
      run: yarn test:ci
