name: Node CI

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3.2.0
      with:
        node-version: 16.x
        cache: 'yarn'
    - name: yarn install
      run: yarn install
    - name: Lint server
      run: yarn lint:server
    - name: Lint client
      run: yarn lint:client
    - name: Lint CSS
      run: yarn lint:css
    - name: Tests
      run: yarn test:ci
