name: Node CI

on:
    push:
    pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Install Node.js
      uses: actions/setup-node@v5.0.0
      with:
        node-version: 22.x
        cache: 'yarn'
    - name: yarn install
      run: yarn install
    - name: Lint server
      run: yarn lint:server
    - name: Lint client
      run: yarn lint:client
    - name: Lint CSS
      run: yarn lint:css
    - name: Install mutool
      run: sudo apt-get install -y mupdf-tools
    - name: Tests
      run: yarn test:ci
